### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by berserkerkz** [jefflessard/tm16xx-display#1]
root@rk3318-box:~/tm16xx-display# make install
make EXTRA_CFLAGS="" -C /lib/modules/6.8.11-edge-rockchip64/build M=/root/tm16xx-display modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.11-edge-rockchip64'
  CC [M]  /root/tm16xx-display/tm16xx.o
/root/tm16xx-display/tm16xx.c:222:6: warning: no previous prototype for ‘hbs658_msb_to_lsb’ [-Wmissing-prototypes]
  222 | void hbs658_msb_to_lsb(u8 *array, size_t length) {
      |      ^~~~~~~~~~~~~~~~~
make[3]: *** No rule to make target 'scripts/mod/modpost', needed by '/root/tm16xx-display/Module.symvers'.  Stop.
make[2]: *** [/usr/src/linux-headers-6.8.11-edge-rockchip64/Makefile:1873: modpost] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.11-edge-rockchip64'
make: *** [Makefile:28: module] Error 2

**Comment by jefflessard** [comment]
It looks like you're encountering an error with the `modpost` script while trying to install kernel module. This error often occurs when the `modpost` script is either missing or not executable.

1. **Check if `modpost` exists**: Ensure that the `modpost` script is present in the `scripts/mod` directory of your kernel source tree `/lib/modules/6.8.11-edge-rockchip64/build`

2. **Make the script executable**: If the script exists but is not executable, you can make it executable by running:
   ```sh
   chmod +x scripts/mod/modpost
   ```
