### ISSUE TITLE
OpenVFD DISPLAY_FLAG_TRANSPOSED not supported

### ISSUE THREAD

**Issue by dreamlayers** [jefflessard/tm16xx-display#4]
The display on my X92 running Armbian Ubuntu Noble 24.04 with kernel 6.6.67 works with https://github.com/arthur-liberman/linux_openvfd but is unusable with this software. This cannot be corrected via the /sys interface because attempts to light multiple segments of one digit actually light segments from multiple digits and even some indicators. This is because for OpenVFD, `vfd_display_type=0x02,0x00,0x01,0x00` and that `0x01` is DISPLAY_FLAG_TRANSPOSED. I don't see any code here to handle this transposing.

**Comment by jefflessard** [comment]
[Latest commit](https://github.com/jefflessard/tm16xx-display/commit/38c727b31d82ccde304bc25f866722e77cc66f35) now includes an experimental transpose_display module parameter.

Please test it out and report if it works as expected or not. Once confirmed to work, I will replace the module parameter by a device tree attribute.

To enable the transpose_display module parameter:
```bash
git pull
make module module-install
rmmod tm16xx
insmod tm16xx.ko transpose_display=1
systemctl restart display
```

Check ``dmesg`` to confirm transpose mode is effectively configured. Should look like:
```
tm16xx 0-0024: Operating in transposed mode
tm16xx 0-0024: Display initialized successfully
```

**Comment by dreamlayers** [comment]
Thank you for the quick response. That certainly does transpose, but it only allows me to set the rightmost digit and indicators. Segments of the rightmost digit of `value` sets indicators, and setting of indicator LEDs controls the rightmost digit. Using `transposed_data |= BIT(7 - j);` corrects the mapping of value to digits and indicator LEDs to indicators. However, I there are some digit segment problems. I am totally unable to light up the centre and top left segments of digits. (This is impossible to fix via segment mapping because nothing lights them up. They do light up properly with OpenVFD.)

**Comment by dreamlayers** [comment]
I was not able to light up those segments because the chip is configured for 5 digit mode: https://github.com/jefflessard/tm16xx-display/blob/38c727b31d82ccde304bc25f866722e77cc66f35/tm16xx.c#L125
In transposed mode, the number of digits must at least equal number of segments to be able to light up all segments. Changing it to 7 digit mode via `MODE = 1 << 1 | 1 << 0` fixed that problem, and also lit up the two indicators to the right of the digits. OpenVFD always uses 7 digit mode for fd628, which seems unnecessary when not transposed.

The only remaining problem was segment mapping. I needed `tm16xx,segment-mapping = [00 01 02 03 04 05 06];`.

**Comment by jefflessard** [comment]
Thanks for your tests and help!

I have updated the code to better manage the transpose and to configure the digit mode dynamically (forcing to 7 digits when transpose is enabled).

I have removed the module parameter and instead replaced it by a `tm16xx,transposed` device tree attribute flag. [x92.dtso](https://github.com/jefflessard/tm16xx-display/blob/268c207c50cd38ae09816dd7ce5b993b115c5348/devices/x92.dtso#L26) has been adjusted accordingly.

You should not need the `transposed_data |= BIT(7 - j);` but you may need to reconfigure grid indexes and segments mapping.

After updating your device tree with the `tm16xx,transposed` flag, you can run the [assisted segments and digits discovery](https://github.com/jefflessard/tm16xx-display/tree/main#assisted-segments-and-digits-disovery) using 
```sh
display-utils -a
```
It will help you identify the digits ordering and the segments mapping. Though, you will have to modify your device tree if the LED icons needs a different grid index.

Please report if now working properly and your adjusted x92.dtso so I can update the one in the git repo.

**Comment by dreamlayers** [comment]
When I tried the new version, nothing lit up on the display. I think the problem is that tm1628_cmd_init() puts multiple commands in the buffer, and then tm16xx_display_flush_init() sends that whole buffer in one single SPI write operation. Each SPI write operation pulls chip select low, holds it low during the whole operation, and then makes it high again. Only the first byte received after the chip select pulls the STB pin low is treated as a command. So the commands after that in the buffer are ignored. Sending individual bytes one at a time in separate SPI transfers from tm16xx_display_flush_init() made it work:

```C
               for (i = 0; i < len; i++)
                       ret = display->client_write(display, &cmd[i], 1);
```

> I have removed the module parameter and instead replaced it by a `tm16xx,transposed` device tree attribute flag. [x92.dtso](https://github.com/jefflessard/tm16xx-display/blob/268c207c50cd38ae09816dd7ce5b993b115c5348/devices/x92.dtso#L26) has been adjusted accordingly.

Nice, thank you, that works.

> You should not need the `transposed_data |= BIT(7 - j);` but you may need to reconfigure grid indexes and segments mapping.

Yes, changing grid indexes can compensate for use of `j` instead of `7 - j`. 

However, both `display-utils -a`  and `/sys/class/leds/display/digits` seem restricted to reordering of digit indexes that are already in use. So, when I have `tm16xx,digits = [00 01 02 03]` in the device tree, and the correct order is `tm16xx,digits = [07 06 05 04];`, both of those seem useless, and I can only reorder digits by manually editing the device tree. I also changed the first number of all indicator reg values from 4 to 3 in the device tree. Everything is properly mapped now. This was easy for me, because I understood device tree syntax well enough and understood that the `7 - j` calculation needs to be performed on those values. But doing it this way may be hard for others. 

It wouldn't be hard to automatically transform other .dtso files in a similar way, and also do the transformation in vfdconf-convert.

This is the segment mapping change. I don't think this is due to transposing. 
```
[03 01 02 06 04 05 00] old
[00 01 02 03 04 05 06] new
```
According to https://github.com/arthur-liberman/linux_openvfd/blob/9264588ba27a964a1e56346202901dd17f9e133d/driver/controllers/fd628.c#L86-L99 table 2 should be used, at https://github.com/arthur-liberman/linux_openvfd/blob/9264588ba27a964a1e56346202901dd17f9e133d/driver/glyphs.h#L83 .  The segment order shown there is the same as the A-G shown by `display-utils`. It seems the wrong old order was incorrectly set by `vfdconf-convert` based on display type. Letters assigned to segments are different in OpenVFD, and this may be confusing.

**Comment by jefflessard** [comment]
Thanks for your valuable insights.

I think the latest changes I've committed should now be the final ones for this issue.

I've refactored the controllers code to explicitly write SPI commands, so STB should now be pulled correctly on each init bytes.

I've also went your way for `transposed_data |= BIT(7 - j);` as this allows 0-based grid index and no additional conversion transformations should be required. Hence, [x92.dtso](https://github.com/jefflessard/tm16xx-display/blob/main/devices/x92.dtso) should not requires you to manually change the LED icons regs anymore.

I've also corrected the dtso files and vfd-convert mapping of vfd_display_type 0x02 to the one you provided.

> However, both `display-utils -a` and `/sys/class/leds/display/digits` seem restricted to reordering of digit indexes that are already in use

Your understanding is correct. Only digits reordering is supported in user space. Modifying the grid indexes in use would add some complexity so I preferred to let that in module probe only, therefore requiring manual device tree editing. After all, this should be a one time discovery and it would not be required after that.

> Letters assigned to segments are different in OpenVFD, and this may be confusing.

I can not speak for OpenVFD, but I've aligned the tm16xx driver on the existing [7 segment mapping of the Linux Kernel](https://github.com/torvalds/linux/blob/master/include/uapi/linux/map_to_7segment.h).

Can you please test the latest changes and confirm that it's now fully working properly? Thanks in advance.

**Comment by dreamlayers** [comment]
> Thanks for your valuable insights.

You're welcome.

> I think the latest changes I've committed should now be the final ones for this issue.

Yes. Everything works now without needing any modifications. Thank you. I am closing this issue.
